apiVersion: v1
kind: Service
metadata:
  name: flask-app-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: flask-app
    release: k8s-monitoring
spec:
  selector:
    app: flask-app
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: {{ .Values.namespace }}
  labels:
    release: k8s-monitoring
spec:
  selector:
    matchLabels:
      app: flask-app
  namespaceSelector:
    matchNames:
      - arsmedicatech
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
