apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.surrealdb.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  user: {{ .Values.surrealdb.secret.user | quote }}
  pass: {{ .Values.surrealdb.secret.pass | quote }}
